### ISSUE TITLE
Optimizing code question

### ISSUE THREAD

**Issue by Chris0016** [todoroff/htdp-space-invaders#1]
Hello, I'm working on the same project now and was noticing that just about everyone followed the same pattern in terms of designing something to remove invaders from an invaders list and the missiles from a missile list/ (AKA a blasting mechanism).  This works fine, but it involves a lot of helper functions which makes the code very wordy. 
So, I was wondering if you had thought of any other more efficient way to do this task or could point me in a solid direction. 
I;m thinking that there probably isn't which means that the fundamental make-struct should be change, but just don't now how.

**Comment by todoroff** [comment]
You shouldn't be concerned with performance optimizations, unless its actually needed. The course's focus is on how to build your programs in a maintainable, readable, and testable way.

Ideally you should split your programs in logical units where each function should have a single purpose and do it well. For example the `advance-game` function is concerned with producing the next game state, but it doesn't need to know or care about the implementation details of how to check for collisions, how to move the entities, etc. It's enough to call the underlying helper functions in the right order and let each do its own thing. Later if you need to change the order of actions, you just change the order of the function calls. Or if you want to refactor the collision detection algorithm, you just make changes to the `destroy-invaders` function and if it passes its tests, you can be confident it will work just fine wherever it's called and not break anything.

You might want to check [this article](https://spin.atomicobject.com/2017/01/09/functions-single-responsibility-principle/) about the single responsibility principle.

Hope that helps!

**Comment by Chris0016** [comment]
Firstly, thanks for the help. It is clear to me this way of systematic design where code is divided into sub-units where each unit responsible for doing a task, and doing it well.  I guess for this project optimization isn't important, but it seemed to be that because of the nature of the game-struct the functions that act on the struct are somewhat limited. In turn, a lot of functions that are similar to each other need to be made for just one mechanism. 
Due to this, I was looking to see if anyone had any different approach to make the game-struct or a  radically different data definition that would make things more compact.
Sorry for not being very clear the first time, but anyways I understand now that this isn't a huge project where optimization is of prime importance, so I shouldn't stress making the cleanest code.

Thanks

**Comment by todoroff** [comment]
@Chris0016 I get what you mean. I believe in the next part of the course you will start making more abstract functions (e.g. map, reduce, filter, etc.) to deal with common tasks.
